---
cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36

install:
  - C:\Python36\python -m pip install tox codecov

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - C:\Python36\scripts\tox

after_test:
  - C:\Python36\scripts\tox -e coverage-report
  - C:\Python36\scripts\codecov
